const lessons=[
 {tab:'1 目的',title:'預選構型的目的',summary:'理解預選設定如何讓衛星在啟動後維持可控、可用與可備援的初始狀態。',slides:[1,2],graphic:'01-preselection-purpose.jpg',visual:'啟動構型導引',nodes:[['初始構型','讓硬體從預定的安全狀態開始。'],['任務就緒','確認衛星可進入下一步作業。'],['可靠運作','以預設機制降低不確定性。']],q:'Pre-selection 最主要的任務是什麼？',o:['定義啟動後的初始構型與硬體狀態','即時調整衛星的軌道','取代所有地面操作'],a:0,n:'先請學生用一句話說明「初始構型」的意義。'},
 {tab:'2 時機',title:'三個關鍵設定時機',summary:'發射前、首次通聯與異常重新開機時，預選程序提供一致且可驗證的設定基準。',slides:[3,4],graphic:'02-configuration-timing.jpg',visual:'時序導航圖',nodes:[['發射前','完成任務前的預先校準。'],['首次通聯','確認衛星與地面之間的設定狀態。'],['ARO','異常重新開機後恢復預定構型。']],q:'哪一個情境最需要使用預選設定來恢復構型？',o:['例行資料整理','異常重新開機（ARO）','每日工作交接'],a:1,n:'比較發射前與 ARO：目的相同，但觸發條件不同。'},
 {tab:'3 PCU',title:'PCU 電力設定',summary:'PCU 協助關鍵電力相關硬體依任務需要進入正確狀態。',slides:[5,6],graphic:'03-pcu-settings.jpg',visual:'電力鏈路檢視',nodes:[['設定來源','預選程序帶入所需設定。'],['PCU','電力控制單元執行對應構型。'],['關鍵硬體','設定後狀態支援後續任務。']],q:'PCU 在本教材中的角色最接近哪一項？',o:['電力控制與相關設定','影像資料壓縮','軌道預報計算'],a:0,n:'請學生找出 PCU 與硬體狀態的關鍵關聯。'},
 {tab:'4 TMTC',title:'TMTC 通訊設定',summary:'透過遙測、遙控與天線切換，讓衛星與地面在正確鏈路上完成確認與操作。',slides:[7,8],graphic:'04-tmtc-settings.jpg',visual:'通訊鏈路演練',nodes:[['遙測','將衛星狀態傳回地面。'],['天線切換','選取可用的通訊路徑。'],['地面確認','由地面站確認設定與鏈路。']],q:'TMTC 設定完成後，最重要的下一步是什麼？',o:['關閉所有通訊','地面確認通訊與設定','忽略遙測資料'],a:1,n:'可請兩位學生分別扮演衛星與地面站。'},
 {tab:'5 指令與備援',title:'指令與備援閉環',summary:'以程序碼及指令將設定、檢查、執行與備援串成可追蹤的可靠操作閉環。',slides:[9],graphic:'05-command-redundancy.jpg',visual:'指令閉環演練',nodes:[['設定','建立需要的指令流程。'],['檢查','確認內容與順序。'],['執行','依程序執行並觀察狀態。'],['備援','異常時依備援方案維持任務。']],q:'設定、檢查、執行、備援的主要價值是什麼？',o:['增加隨機性','建立可驗證的可靠操作閉環','減少地面確認'],a:1,n:'請學生指出閉環中最容易被忽略的一步。'}];
let lessonIndex=0,slideIndex=0,teacher=false,seconds=120,timerId,inkColor='#f6df8b',drawing=false;const $=q=>document.querySelector(q);
function render(){const x=lessons[lessonIndex];$('.focus-tabs').innerHTML=lessons.map((v,i)=>`<button class="${i===lessonIndex?'active':''}" data-i="${i}">${v.tab}</button>`).join('');$('.focus-tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{lessonIndex=+b.dataset.i;slideIndex=0;render()});$('#focusTitle').textContent=x.title;$('#focusSummary').textContent=x.summary;$('#progressText').textContent=`${lessonIndex+1} / 5`;$('#progressBar').style.width=`${(lessonIndex+1)*20}%`;$('#visualTitle').textContent=x.visual;$('#questionText').textContent=x.q;$('#teacherNote span').textContent=x.n;$('#quizStatus').textContent='尚未作答';$('#feedback').textContent='';$('#feedback').className='feedback';$('#infographicImage').src=`./assets/${x.graphic}`;$('#downloadGraphic').href=`./assets/${x.graphic}`;renderSlide();renderVisual();renderQuiz()}
function renderSlide(){const x=lessons[lessonIndex],n=x.slides[slideIndex];$('#slideImage').src=`./assets/slide-${String(n).padStart(2,'0')}.jpg`;$('#slideCount').textContent=`${slideIndex+1} / ${x.slides.length}`;$('#slideDots').innerHTML=x.slides.map((_,i)=>`<span class="dot ${i===slideIndex?'active':''}"></span>`).join('')}
function renderVisual(){const x=lessons[lessonIndex],m=$('#visualMap');m.innerHTML=x.nodes.map((n,i)=>`<button class="orbit-node ${i===0?'active':''}" style="left:${12+(i%2)*48}%;top:${i<2?20:94}px" data-i="${i}">${n[0]}</button>`).join('');m.querySelectorAll('button').forEach(b=>b.onclick=()=>{const i=+b.dataset.i;m.querySelectorAll('button').forEach(k=>k.classList.toggle('active',k===b));$('#visualStepTitle').textContent=x.nodes[i][0];$('#visualStepCopy').textContent=x.nodes[i][1]});$('#visualStepTitle').textContent=x.nodes[0][0];$('#visualStepCopy').textContent=x.nodes[0][1]}
function renderQuiz(){const x=lessons[lessonIndex];$('#answerOptions').innerHTML=x.o.map((v,i)=>`<button data-i="${i}" data-correct="${i===x.a}">${'ABC'[i]}. ${v}</button>`).join('');$('#answerOptions').querySelectorAll('button').forEach(b=>b.onclick=()=>{const ok=+b.dataset.i===x.a;$('#answerOptions').querySelectorAll('button').forEach(k=>k.classList.toggle('selected',k===b));$('#quizStatus').textContent=ok?'答對了':'再想一想';$('#feedback').textContent=ok?'✓ 正確：你已掌握這個重點。':'提示：回看簡報與資訊圖表後再試一次。';$('#feedback').className=`feedback ${ok?'correct':'wrong'}`})}
$('#previousSlide').onclick=()=>{const x=lessons[lessonIndex];slideIndex=(slideIndex-1+x.slides.length)%x.slides.length;renderSlide()};$('#nextSlide').onclick=()=>{const x=lessons[lessonIndex];slideIndex=(slideIndex+1)%x.slides.length;renderSlide()};$('#modeToggle').onclick=()=>{teacher=!teacher;document.body.classList.toggle('teacher',teacher);$('#modeToggle').textContent=teacher?'教師模式':'學生模式';resizeCanvas()};
const names=['宥辰','芷妍','承翰','予晴','柏宇','品妍','昱廷','思妤'];$('#drawStudent').onclick=()=>$('#pickedName').textContent=names[Math.floor(Math.random()*names.length)];function tick(){seconds--;if(seconds<1){seconds=0;clearInterval(timerId);timerId=null;$('#timerStart').textContent='開始'}$('#timerDisplay').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`};$('#timerStart').onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;$('#timerStart').textContent='繼續'}else{timerId=setInterval(tick,1000);$('#timerStart').textContent='暫停'}};$('#timerReset').onclick=()=>{clearInterval(timerId);timerId=null;seconds=120;$('#timerDisplay').textContent='02:00';$('#timerStart').textContent='開始'};$('#dockToggle').onclick=()=>{$('.tool-dock').classList.toggle('dock-collapsed')};$('#penToggle').onclick=()=>{const p=$('.pen-dock');p.classList.toggle('open');$('#penToggle').setAttribute('aria-expanded',p.classList.contains('open'))};document.querySelectorAll('.pen-color').forEach(b=>b.onclick=()=>{inkColor=b.dataset.color;document.querySelectorAll('.pen-color').forEach(k=>k.classList.toggle('active',k===b))});
const canvas=$('#inkCanvas'),ctx=canvas.getContext('2d');function resizeCanvas(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=4}resizeCanvas();addEventListener('resize',resizeCanvas);canvas.onpointerdown=e=>{if(!teacher)return;drawing=true;ctx.beginPath();ctx.moveTo(e.clientX,e.clientY)};canvas.onpointermove=e=>{if(!drawing)return;ctx.strokeStyle=inkColor;ctx.lineTo(e.clientX,e.clientY);ctx.stroke()};addEventListener('pointerup',()=>drawing=false);$('#clearInk').onclick=()=>ctx.clearRect(0,0,canvas.width,canvas.height);render();
